"""
Modern visual theme: eighteen curated color palettes, a dynamic "Match
System Appearance" theme, and a fully custom one, font resolution, ttk
styling, and canvas drawing helpers (rounded rects, logo mark,
theme-swatch previews) shared across the app.

Colors are exposed as plain module attributes (theme.PANEL_BG, etc.) so
existing code can keep reading `theme.SOMETHING` without changes. What
switches at runtime is *which* palette those names point at -- call
set_theme("theme_id") to flip them, then re-run apply_theme(root) and
rebuild any plain (non-ttk) widgets so they pick up the new colors (ttk
widgets update automatically via the style engine; raw tk widgets like
Frame/Label/Canvas cache their bg/fg at construction time and need to be
rebuilt -- see MainWindow._apply_theme_and_rebuild).

This used to be a hand-tuned set of seven palettes, each with all ~24
colors picked independently. It's now eighteen palettes -- inspired by
the mood categories (Monochromatic, Romantic, Playful, Vibrant, Neutral,
Tranquil, Seasonal) on Figma's "100 color combinations" resource
(figma.com/resource-library/color-combinations) -- plus "Match System
Appearance", which follows the OS's light/dark setting instead of being
hand-picked, and a "Custom" entry the user builds themselves from a
color picker (see panels.SettingsPanel's custom-color row). Rather than hand-picking all
~24 colors per palette again (error-prone at this count, and the whole
point of a user-driven custom option), every palette -- curated or
custom alike -- is generated by derive_palette() below from just a
handful of seed colors: a background, a panel color, a primary text
color, and an accent. Everything else (borders, muted text, hover/soft
accent tints, grid lines, etc.) is computed from those four using the
same proportional relationships the original seven hand-tuned palettes
actually had (verified by measuring them before writing this).
"""
import math
import subprocess
import sys
import tkinter.font as tkfont
from tkinter import ttk

# ---------------------------------------------------------------------------
# Color math -- small helpers used only to derive a full ~24-color palette
# from a handful of seed colors (see derive_palette below).
# ---------------------------------------------------------------------------
def _hex_to_rgb(hex_color: str):
    h = hex_color.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _rgb_to_hex(rgb) -> str:
    return "#{:02X}{:02X}{:02X}".format(*(max(0, min(255, round(c))) for c in rgb))


def _mix(color_a: str, color_b: str, t: float) -> str:
    """Blend from color_a toward color_b by fraction t (0 = color_a,
    1 = color_b), in plain sRGB. Not perceptually uniform, but plenty
    good enough at the small t values every derived color below uses,
    and it's what the hand-tuned originals turn out to approximate too."""
    a, b = _hex_to_rgb(color_a), _hex_to_rgb(color_b)
    return _rgb_to_hex(a[i] + (b[i] - a[i]) * t for i in range(3))


def _darken(color: str, amount: float) -> str:
    """Multiply each channel toward black by `amount` (0 = unchanged,
    1 = black) -- used for ACCENT_HOVER, a plain darken rather than a mix
    toward some other color."""
    r, g, b = _hex_to_rgb(color)
    factor = 1.0 - amount
    return _rgb_to_hex((r * factor, g * factor, b * factor))


def _is_dark(color: str) -> bool:
    """Perceptual-ish luminance check used only to decide which side of a
    couple of mode-dependent rules (FIELD_BG, SURFACE, default danger/now
    -line colors) a seed palette falls on -- there's no separate light/
    dark toggle the user sets; it's inferred from the panel color itself."""
    r, g, b = _hex_to_rgb(color)
    luminance = 0.299 * r + 0.587 * g + 0.114 * b
    return luminance < 128


def derive_palette(app_bg: str, panel_bg: str, text_primary: str, accent: str,
                    danger: str = None, now_line: str = None) -> dict:
    """Build a full ~24-color palette from four required seed colors (an
    app background, a panel/card background, a primary text color, and an
    accent) plus two optional ones (a danger/delete red and a "now" line
    color -- sensible mode-appropriate defaults are used if omitted).

    This is the one place that turns "a few colors someone picked" into
    "a fully-themed app" -- used for every one of the twenty curated
    palettes below (each just supplies its own seeds) and for the user's
    own Custom palette (panels.SettingsPanel's four color pickers feed
    straight into this)."""
    dark = _is_dark(panel_bg)
    if danger is None:
        danger = "#E5484D" if dark else "#D6334C"
    if now_line is None:
        now_line = "#FF9500" if dark else "#FF5A36"

    field_bg = _mix(panel_bg, text_primary, 0.035) if dark else panel_bg
    accent_hover = _darken(accent, 0.17)
    accent_soft = _mix(panel_bg, accent, 0.11)

    return {
        "APP_BG": app_bg,
        "PANEL_BG": panel_bg,
        "BORDER": _mix(panel_bg, text_primary, 0.065),
        "BORDER_STRONG": _mix(panel_bg, text_primary, 0.12),
        "TEXT_PRIMARY": text_primary,
        "TEXT_SECONDARY": _mix(text_primary, panel_bg, 0.38),
        "TEXT_MUTED": _mix(text_primary, panel_bg, 0.63),
        "ACCENT": accent,
        "ACCENT_HOVER": accent_hover,
        "ACCENT_SOFT": accent_soft,
        "DANGER": danger,
        "DANGER_SOFT": _mix(panel_bg, danger, 0.08),
        "DANGER_SOFT_ACTIVE": _mix(panel_bg, danger, 0.16),
        "GRID_LINE": _mix(panel_bg, text_primary, 0.04),
        "GRID_LINE_HOUR": _mix(panel_bg, text_primary, 0.10),
        "HEADER_BG": _mix(panel_bg, text_primary, 0.045),
        "TODAY_TINT": accent_soft,
        "NOW_LINE": now_line,
        "BLOCK_BORDER": panel_bg,
        "SELECTION_OUTLINE": text_primary,
        "PREVIEW_FILL": accent,
        "PREVIEW_OUTLINE": accent_hover,
        "FIELD_BG": field_bg,
        "SURFACE": field_bg if dark else app_bg,
    }


# ---------------------------------------------------------------------------
# Eighteen curated palettes -- two to four per Figma mood category, a mix
# of light and dark, each defined as just a handful of seeds (see
# derive_palette above). "category" is metadata only (shown in the
# Settings description text) -- THEME_ORDER below is the actual display
# order, grouped by category so related palettes sit together.
# ---------------------------------------------------------------------------
_PRESETS = [
    ("stormy_morning", "Stormy Morning", "Monochromatic",
     "Charcoal and slate-blue in one family -- calm, restrained, all business.",
     dict(app_bg="#0B0E13", panel_bg="#12161D", text_primary="#EDEFF3", accent="#5B7CA3")),
    ("mossy_hollow", "Mossy Hollow", "Monochromatic",
     "Deep forest green throughout, one quiet hue from background to accent.",
     dict(app_bg="#0A0F0B", panel_bg="#101712", text_primary="#E9F2EA", accent="#4C7A58")),
    ("ink_wash", "Ink Wash", "Monochromatic",
     "Paper white and charcoal ink -- a light monochrome, nothing but gray and near-black.",
     dict(app_bg="#F3F3F4", panel_bg="#FFFFFF", text_primary="#17181C", accent="#3A3D46",
          danger="#C4314B", now_line="#E4572E")),

    ("blooming_romance", "Blooming Romance", "Romantic",
     "Soft blush pink on white -- warm and romantic without tipping into saccharine.",
     dict(app_bg="#FDF4F6", panel_bg="#FFFFFF", text_primary="#3A1420", accent="#D6537B",
          danger="#C0293F", now_line="#E08A2E")),
    ("lavender_fields", "Lavender Fields", "Romantic",
     "Pale lavender and soft violet -- gentle, a little dreamy.",
     dict(app_bg="#F6F3FC", panel_bg="#FFFFFF", text_primary="#2A1F3D", accent="#8B6FD6",
          danger="#D6455E", now_line="#E0932E")),
    ("evening_rose", "Evening Rose", "Romantic",
     "Deep rose on near-black -- the same romantic pink family, after dark.",
     dict(app_bg="#170D12", panel_bg="#21131A", text_primary="#F7E9EE", accent="#E8608A",
          danger="#FF6B6B", now_line="#FFB454")),

    ("zesty_lemon", "Zesty Lemon", "Playful",
     "Bright and citrusy -- a mustard-gold accent on a warm cream background.",
     dict(app_bg="#FDFBEF", panel_bg="#FFFFFF", text_primary="#2B2610", accent="#C99A00",
          danger="#D6334C", now_line="#2F6FED")),
    ("bubblegum_pop", "Bubblegum Pop", "Playful",
     "Hot pink on near-black -- loud, neon, unmistakably playful.",
     dict(app_bg="#0F0A14", panel_bg="#17101F", text_primary="#FBEFFF", accent="#FF4FD8",
          danger="#FF4D6D", now_line="#7CFF6B")),
    ("electric_kiwi", "Electric Kiwi", "Playful",
     "Lime green on near-black -- sharp, energetic, a little irreverent.",
     dict(app_bg="#0A0F08", panel_bg="#10160D", text_primary="#EFFCE9", accent="#84C400",
          danger="#FF5D5D", now_line="#FF9F1C")),

    ("cobalt_rush", "Cobalt Rush", "Vibrant",
     "Electric blue on near-black -- high-contrast and confident.",
     dict(app_bg="#05070F", panel_bg="#0B1020", text_primary="#EAF0FF", accent="#2F6FED",
          danger="#FF3B5C", now_line="#FF9500")),
    ("magenta_pulse", "Magenta Pulse", "Vibrant",
     "Rich magenta on deep violet-black -- vivid and a little electric.",
     dict(app_bg="#0F0714", panel_bg="#180D22", text_primary="#F5EAFB", accent="#C93BE0",
          danger="#FF4D6D", now_line="#FFB454")),

    ("slate_graphite", "Slate Graphite", "Neutral",
     "Cool graphite gray with a muted steel accent -- quiet and professional.",
     dict(app_bg="#0E0F11", panel_bg="#16181B", text_primary="#EDEEF0", accent="#6E7681",
          danger="#E5484D", now_line="#F2994A")),
    ("sandstone", "Sandstone", "Neutral",
     "Warm sand tones with a muted clay accent -- soft daylight neutrality.",
     dict(app_bg="#F5EFE6", panel_bg="#FFFDF9", text_primary="#2E2A22", accent="#B08A5A",
          danger="#C1442E", now_line="#4C7A58")),

    ("ocean_mist", "Ocean Mist", "Tranquil",
     "Pale sea-glass teal on white -- light, airy, easy on the eyes.",
     dict(app_bg="#F0F6F6", panel_bg="#FFFFFF", text_primary="#123435", accent="#2A9D8F",
          danger="#C0293F", now_line="#E76F51")),
    ("sage_retreat", "Sage Retreat", "Tranquil",
     "Soft sage green on white -- calm, natural, unhurried.",
     dict(app_bg="#F3F6F1", panel_bg="#FFFFFF", text_primary="#1F2E1A", accent="#6E9B6B",
          danger="#C1442E", now_line="#D97706")),
    ("midnight_lagoon", "Midnight Lagoon", "Tranquil",
     "Deep teal on near-black -- the same calm sea-glass family, after dark.",
     dict(app_bg="#060F11", panel_bg="#0C1A1D", text_primary="#E4F5F5", accent="#17A6A0",
          danger="#FF5D5D", now_line="#FFB454")),

    ("autumn_harvest", "Autumn Harvest", "Seasonal",
     "Toasted brown and burnt orange -- a cozy, low-light autumn palette.",
     dict(app_bg="#140D08", panel_bg="#1F140C", text_primary="#FBEEE1", accent="#E08A2E",
          danger="#C1442E", now_line="#7CA84C")),
    ("winter_frost", "Winter Frost", "Seasonal",
     "Icy pale blue on white -- crisp, clean, a little wintry.",
     dict(app_bg="#F2F7FB", panel_bg="#FFFFFF", text_primary="#142433", accent="#4E7CB8",
          danger="#C0293F", now_line="#E0932E")),
]

THEMES = {
    theme_id: {
        "label": label,
        "description": description,
        "category": category,
        "palette": derive_palette(**seeds),
    }
    for theme_id, label, category, description, seeds in _PRESETS
}

CUSTOM_THEME_ID = "custom"

# Like "custom", "system" isn't a fixed entry in THEMES either -- it's a
# live palette that follows the OS's current light/dark appearance
# setting instead of user-picked seed colors. Unlike "custom" though, it
# IS included in THEME_ORDER (at the very front -- see below), since it's
# meant to be the obvious first choice rather than an opt-in extra.
SYSTEM_THEME_ID = "system"

# Display order for the Settings picker -- "system" first, then the
# eighteen curated ids above grouped by category (Monochromatic,
# Romantic, Playful, Vibrant, Neutral, Tranquil, Seasonal), in the same
# order _PRESETS lists them. "custom" is NOT in here -- it's appended
# separately wherever the picker is drawn (see
# panels.SettingsPanel._build_theme_grid), since it isn't a fixed
# palette but a live one built from the user's own seed colors below.
THEME_ORDER = [SYSTEM_THEME_ID] + [theme_id for theme_id, *_ in _PRESETS]

DEFAULT_THEME_ID = SYSTEM_THEME_ID

# Anyone upgrading from the old seven-palette system (or the light/dark
# toggle before that) gets mapped onto the closest match among the new
# twenty rather than losing their preference outright.
_LEGACY_MODE_MAP = {
    "light": "winter_frost", "dark": "stormy_morning",
    "sleek_indigo": "stormy_morning", "neon_cyan": "cobalt_rush",
    "crisp_light": "winter_frost", "emerald_terminal": "mossy_hollow",
    "warm_amber": "sandstone", "violet_nebula": "magenta_pulse",
    "mac_glass": "ocean_mist",
}

# The user's own Custom palette -- four seed colors (background, panel,
# text, accent), defaulting to Cobalt Rush's until they pick their own via
# panels.SettingsPanel's color pickers. Persisted separately (see
# get_custom_seeds/set_custom_seeds and main_window.py's startup load) so
# it survives restarts even when "custom" isn't the active theme.
_custom_seeds = dict(app_bg="#05070F", panel_bg="#0B1020", text_primary="#EAF0FF", accent="#2F6FED")


def get_custom_seeds() -> dict:
    return dict(_custom_seeds)


def set_custom_seeds(app_bg: str, panel_bg: str, text_primary: str, accent: str):
    """Update the Custom palette's seed colors. Safe to call freely while
    the user is still picking colors in Settings (see
    panels.SettingsPanel) -- it only changes what the "custom" theme id
    resolves to; it doesn't touch whichever palette is actually active
    until/unless set_theme("custom") is called too."""
    _custom_seeds.update(app_bg=app_bg, panel_bg=panel_bg, text_primary=text_primary, accent=accent)


# Seed colors for "Match System Appearance" -- fixed, unlike "custom"'s
# user-picked ones, since this theme doesn't ask the user anything; it
# just picks one of these two sets for itself based on the OS's current
# appearance (see _detect_system_is_dark below). Same accent both ways
# for a bit of brand continuity between the light and dark look.
_SYSTEM_SEEDS_LIGHT = dict(app_bg="#F4F6FA", panel_bg="#FFFFFF", text_primary="#161B22", accent="#2F6FED")
_SYSTEM_SEEDS_DARK = dict(app_bg="#0B0E14", panel_bg="#12161F", text_primary="#EAF0FF", accent="#2F6FED")

_system_is_dark_cache = None


def _detect_system_is_dark() -> bool:
    """Best-effort, once-per-run check of the OS's current light/dark
    appearance setting, cached after the first call -- this is checked
    only at startup, not polled live, so if the user flips their OS
    appearance while the app is open the "Match System Appearance" theme
    won't follow until the app is restarted. Falls back to dark (this
    app's own long-standing default look) on any unsupported platform or
    failed check -- a themed-wrong app beats one that crashes on
    startup."""
    global _system_is_dark_cache
    if _system_is_dark_cache is not None:
        return _system_is_dark_cache
    is_dark = True
    if sys.platform == "darwin":
        try:
            result = subprocess.run(
                ["defaults", "read", "-g", "AppleInterfaceStyle"],
                capture_output=True, text=True, timeout=2,
            )
            # macOS only *sets* this key when Dark mode is active -- a
            # missing key (non-zero exit, empty stdout) means Light mode.
            is_dark = result.returncode == 0 and result.stdout.strip().lower() == "dark"
        except Exception:
            pass
    elif sys.platform == "win32":
        try:
            import winreg
            key = winreg.OpenKey(
                winreg.HKEY_CURRENT_USER,
                r"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize",
            )
            value, _ = winreg.QueryValueEx(key, "AppsUseLightTheme")
            is_dark = value == 0
        except Exception:
            pass
    _system_is_dark_cache = is_dark
    return is_dark


def get_theme(theme_id: str) -> dict:
    """Look up a theme's {label, description, palette} by id, including
    the special "custom" id -- which isn't a fixed entry in THEMES, but is
    built live from whatever set_custom_seeds() last stored, so it always
    reflects the user's current picks even before they've hit Save."""
    theme_id = resolve_theme_id(theme_id)
    if theme_id == CUSTOM_THEME_ID:
        return {
            "label": "Custom",
            "description": "Your own palette -- pick a background, panel, text, and accent "
                            "color below and the rest is filled in to match.",
            "palette": derive_palette(**_custom_seeds),
        }
    if theme_id == SYSTEM_THEME_ID:
        seeds = _SYSTEM_SEEDS_DARK if _detect_system_is_dark() else _SYSTEM_SEEDS_LIGHT
        return {
            "label": "System",
            "description": "Match System Appearance -- follows your Mac or Windows "
                            "light/dark setting. Checked once when the app starts; "
                            "switching your OS appearance while the app is open won't "
                            "change it until you restart.",
            "palette": derive_palette(**seeds),
        }
    return THEMES[theme_id]


def resolve_theme_id(value) -> str:
    """Turn a stored settings value (a current theme id, a legacy "light"/
    "dark" mode string or old palette id, or anything else/missing) into
    a valid theme id -- one of the twenty curated ids or "custom"."""
    if value == CUSTOM_THEME_ID or value == SYSTEM_THEME_ID or value in THEMES:
        return value
    if value in _LEGACY_MODE_MAP:
        return _LEGACY_MODE_MAP[value]
    return DEFAULT_THEME_ID


CURRENT_THEME_ID = DEFAULT_THEME_ID

# Explicit module-level bindings for every palette key (rather than only
# setting them dynamically inside set_theme()) so static analysis sees real
# top-level names -- `theme.PANEL_BG` etc. -- instead of attributes that
# only exist at runtime. set_theme() below reassigns each of these via an
# explicit `global` statement, which keeps both static analysis and the
# runtime dynamic-repaint behavior working.
_DEFAULT_PALETTE = get_theme(DEFAULT_THEME_ID)["palette"]
APP_BG: str = _DEFAULT_PALETTE["APP_BG"]
PANEL_BG: str = _DEFAULT_PALETTE["PANEL_BG"]
BORDER: str = _DEFAULT_PALETTE["BORDER"]
BORDER_STRONG: str = _DEFAULT_PALETTE["BORDER_STRONG"]
TEXT_PRIMARY: str = _DEFAULT_PALETTE["TEXT_PRIMARY"]
TEXT_SECONDARY: str = _DEFAULT_PALETTE["TEXT_SECONDARY"]
TEXT_MUTED: str = _DEFAULT_PALETTE["TEXT_MUTED"]
ACCENT: str = _DEFAULT_PALETTE["ACCENT"]
ACCENT_HOVER: str = _DEFAULT_PALETTE["ACCENT_HOVER"]
ACCENT_SOFT: str = _DEFAULT_PALETTE["ACCENT_SOFT"]
DANGER: str = _DEFAULT_PALETTE["DANGER"]
DANGER_SOFT: str = _DEFAULT_PALETTE["DANGER_SOFT"]
DANGER_SOFT_ACTIVE: str = _DEFAULT_PALETTE["DANGER_SOFT_ACTIVE"]
GRID_LINE: str = _DEFAULT_PALETTE["GRID_LINE"]
GRID_LINE_HOUR: str = _DEFAULT_PALETTE["GRID_LINE_HOUR"]
HEADER_BG: str = _DEFAULT_PALETTE["HEADER_BG"]
TODAY_TINT: str = _DEFAULT_PALETTE["TODAY_TINT"]
NOW_LINE: str = _DEFAULT_PALETTE["NOW_LINE"]
BLOCK_BORDER: str = _DEFAULT_PALETTE["BLOCK_BORDER"]
SELECTION_OUTLINE: str = _DEFAULT_PALETTE["SELECTION_OUTLINE"]
PREVIEW_FILL: str = _DEFAULT_PALETTE["PREVIEW_FILL"]
PREVIEW_OUTLINE: str = _DEFAULT_PALETTE["PREVIEW_OUTLINE"]
FIELD_BG: str = _DEFAULT_PALETTE["FIELD_BG"]
SURFACE: str = _DEFAULT_PALETTE["SURFACE"]
GRID_BG: str = PANEL_BG  # canvas background -- always mirrors PANEL_BG


def set_theme(theme_id: str):
    """Point every color constant in this module at the given theme id
    (one of THEMES, or "custom" -- see get_theme above). Falls back to
    the default / maps legacy light-dark values via resolve_theme_id() on
    anything else."""
    global CURRENT_THEME_ID, APP_BG, PANEL_BG, BORDER, BORDER_STRONG, TEXT_PRIMARY, \
        TEXT_SECONDARY, TEXT_MUTED, ACCENT, ACCENT_HOVER, ACCENT_SOFT, DANGER, DANGER_SOFT, \
        DANGER_SOFT_ACTIVE, GRID_LINE, GRID_LINE_HOUR, HEADER_BG, TODAY_TINT, NOW_LINE, \
        BLOCK_BORDER, SELECTION_OUTLINE, PREVIEW_FILL, PREVIEW_OUTLINE, FIELD_BG, SURFACE, GRID_BG

    theme_id = resolve_theme_id(theme_id)
    CURRENT_THEME_ID = theme_id
    p = get_theme(theme_id)["palette"]

    APP_BG = p["APP_BG"]
    PANEL_BG = p["PANEL_BG"]
    BORDER = p["BORDER"]
    BORDER_STRONG = p["BORDER_STRONG"]
    TEXT_PRIMARY = p["TEXT_PRIMARY"]
    TEXT_SECONDARY = p["TEXT_SECONDARY"]
    TEXT_MUTED = p["TEXT_MUTED"]
    ACCENT = p["ACCENT"]
    ACCENT_HOVER = p["ACCENT_HOVER"]
    ACCENT_SOFT = p["ACCENT_SOFT"]
    DANGER = p["DANGER"]
    DANGER_SOFT = p["DANGER_SOFT"]
    DANGER_SOFT_ACTIVE = p["DANGER_SOFT_ACTIVE"]
    GRID_LINE = p["GRID_LINE"]
    GRID_LINE_HOUR = p["GRID_LINE_HOUR"]
    HEADER_BG = p["HEADER_BG"]
    TODAY_TINT = p["TODAY_TINT"]
    NOW_LINE = p["NOW_LINE"]
    BLOCK_BORDER = p["BLOCK_BORDER"]
    SELECTION_OUTLINE = p["SELECTION_OUTLINE"]
    PREVIEW_FILL = p["PREVIEW_FILL"]
    PREVIEW_OUTLINE = p["PREVIEW_OUTLINE"]
    FIELD_BG = p["FIELD_BG"]
    SURFACE = p["SURFACE"]
    GRID_BG = PANEL_BG


def get_theme_id() -> str:
    return CURRENT_THEME_ID


def theme_label(theme_id: str) -> str:
    return get_theme(theme_id)["label"]


# Populate the module-level constants immediately so `theme.PANEL_BG` etc.
# work for any code that imports this module before a Database/settings
# lookup has a chance to call set_theme() with the user's saved preference.
set_theme(DEFAULT_THEME_ID)

_FONT_FAMILY = None


def resolve_font_family(root=None) -> str:
    """Pick the best-looking sans-serif font available on this machine.

    Must be called after a Tk root exists (tkfont.families() needs one).
    Cached after the first call.
    """
    global _FONT_FAMILY
    if _FONT_FAMILY is not None:
        return _FONT_FAMILY
    preferred = ["Segoe UI", "SF Pro Text", "Helvetica Neue", "Helvetica",
                 "Ubuntu", "Cantarell", "Noto Sans", "Arial", "DejaVu Sans"]
    try:
        available = set(tkfont.families(root))
    except Exception:
        available = set()
    for name in preferred:
        if name in available:
            _FONT_FAMILY = name
            break
    else:
        _FONT_FAMILY = "TkDefaultFont"
    return _FONT_FAMILY


def font(root=None, size=10, weight="normal"):
    return (resolve_font_family(root), size, weight)


def apply_theme(root):
    """Configure global widget defaults + ttk styles for the whole app,
    using whatever palette set_theme() last selected. Safe to call again
    after switching themes -- ttk widgets re-render immediately since ttk
    styles are looked up dynamically; plain tk widgets do not and must be
    rebuilt separately (see MainWindow._apply_theme_and_rebuild)."""
    family = resolve_font_family(root)

    root.configure(bg=APP_BG)
    # Sets the default font for every classic Tk widget (Label, Button,
    # Text, Listbox, Menu, ...) app-wide in one shot.
    root.option_add("*Font", (family, 10))
    root.option_add("*Menu.background", PANEL_BG)
    root.option_add("*Menu.foreground", TEXT_PRIMARY)
    root.option_add("*Menu.activeBackground", ACCENT_SOFT)
    root.option_add("*Menu.activeForeground", ACCENT)
    root.option_add("*Menu.borderWidth", 1)

    # A ttk.Combobox's dropdown list is a plain classic-Tk Listbox under the
    # hood, which does NOT pick up ttk styling -- left alone it renders with
    # Tk's own default colors (typically black-on-white) regardless of
    # theme, which stands out as an unreadable/jarring flash against a dark
    # panel. Themed explicitly here so every dropdown (Activity, Day,
    # Start/End time, Theme picker, etc.) matches whichever theme is active.
    root.option_add("*TCombobox*Listbox.background", FIELD_BG)
    root.option_add("*TCombobox*Listbox.foreground", TEXT_PRIMARY)
    root.option_add("*TCombobox*Listbox.selectBackground", ACCENT)
    root.option_add("*TCombobox*Listbox.selectForeground", "#FFFFFF")

    style = ttk.Style(root)
    try:
        style.theme_use("clam")
    except Exception:
        pass

    style.configure("TFrame", background=PANEL_BG)
    style.configure("App.TFrame", background=APP_BG)
    style.configure("Card.TFrame", background=PANEL_BG)

    style.configure("TLabel", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 10))
    style.configure("Secondary.TLabel", background=PANEL_BG, foreground=TEXT_SECONDARY, font=(family, 9))
    style.configure("Heading.TLabel", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 18, "bold"))

    # Primary (accent) button
    style.configure("Accent.TButton", background=ACCENT, foreground="white",
                     font=(family, 10, "bold"), padding=(14, 8), borderwidth=0, relief="flat")
    style.map("Accent.TButton",
              background=[("active", ACCENT_HOVER), ("pressed", ACCENT_HOVER)],
              foreground=[("disabled", TEXT_MUTED)])

    # Secondary (neutral) button. Idle fill is SURFACE, not APP_BG -- APP_BG
    # is the app's own base/outermost layer, darker than the PANEL_BG these
    # buttons actually sit on in every dark theme, which made them read as a
    # dim, sunken notch instead of a button. SURFACE is deliberately a step
    # *lighter* than PANEL_BG in dark themes (mirroring how BORDER/
    # BORDER_STRONG already correctly lighten further on hover/press) while
    # keeping the original APP_BG look for light themes, where a slightly
    # darker idle fill reads fine. See widgets._BUTTON_STYLES for the actual
    # hand-drawn RoundedButton this app renders (this ttk style is now
    # unused directly but kept in sync so it isn't a stale trap later).
    style.configure("Secondary.TButton", background=SURFACE, foreground=TEXT_PRIMARY,
                     font=(family, 10), padding=(10, 6), borderwidth=0, relief="flat")
    style.map("Secondary.TButton", background=[("active", BORDER), ("pressed", BORDER_STRONG)])

    # Small nav (‹ Today ›) buttons -- same reasoning as Secondary above:
    # hover should get more prominent than idle, which means lighter (not
    # darker) once the surrounding panel is itself dark.
    style.configure("Nav.TButton", background=PANEL_BG, foreground=TEXT_PRIMARY,
                     font=(family, 10), padding=(8, 5), borderwidth=1, relief="flat")
    style.map("Nav.TButton", background=[("active", SURFACE)], bordercolor=[("!disabled", BORDER_STRONG)])

    style.configure("Danger.TButton", background=DANGER_SOFT, foreground=DANGER,
                     font=(family, 10), padding=(10, 6), borderwidth=0, relief="flat")
    style.map("Danger.TButton", background=[("active", DANGER_SOFT_ACTIVE)])

    style.configure("TEntry", fieldbackground=FIELD_BG, foreground=TEXT_PRIMARY, padding=6,
                     borderwidth=1, relief="flat", bordercolor=BORDER_STRONG,
                     insertcolor=TEXT_PRIMARY)
    style.configure("TCombobox", fieldbackground=FIELD_BG, background=FIELD_BG, foreground=TEXT_PRIMARY,
                     padding=6, borderwidth=1, relief="flat", arrowsize=14)
    style.map("TCombobox", fieldbackground=[("readonly", FIELD_BG)],
              selectbackground=[("readonly", FIELD_BG)], selectforeground=[("readonly", TEXT_PRIMARY)],
              foreground=[("readonly", TEXT_PRIMARY)])

    style.configure("Big.TLabel", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 12))
    style.configure("Big.TEntry", fieldbackground=FIELD_BG, foreground=TEXT_PRIMARY, padding=10,
                     borderwidth=1, relief="flat", bordercolor=BORDER_STRONG,
                     insertcolor=TEXT_PRIMARY, font=(family, 12))
    style.configure("Big.TCombobox", fieldbackground=FIELD_BG, background=FIELD_BG, foreground=TEXT_PRIMARY,
                     padding=10, borderwidth=1, relief="flat", arrowsize=16, font=(family, 12))
    style.map("Big.TCombobox", fieldbackground=[("readonly", FIELD_BG)],
              selectbackground=[("readonly", FIELD_BG)], selectforeground=[("readonly", TEXT_PRIMARY)],
              foreground=[("readonly", TEXT_PRIMARY)])
    style.configure("Big.TCheckbutton", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 12))

    style.configure("TRadiobutton", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 10))
    style.configure("TCheckbutton", background=PANEL_BG, foreground=TEXT_PRIMARY, font=(family, 10))
    # The "clam" base theme's own Checkbutton/Radiobutton style swaps in a
    # bright default background the moment the mouse is over it (its
    # built-in "active" state color, never overridden above) -- jarring
    # against a themed, often-dark panel. Pinning "active" back to the
    # same PANEL_BG as everything else removes that flash entirely rather
    # than just picking a softer replacement color.
    style.map("TCheckbutton", background=[("active", PANEL_BG)])
    style.map("Big.TCheckbutton", background=[("active", PANEL_BG)])
    style.map("TRadiobutton", background=[("active", PANEL_BG)])

    # Tab bar: ttk.Notebook's own native tab strip is square-cornered with
    # no way to round it short of per-theme 9-slice image assets (this app
    # has none, deliberately -- see requirements.txt) or replacing it with
    # hand-drawn RoundedButton toggles the way MainWindow._build_body does
    # (its own tab_bar row, driving this same notebook via .select()).
    #
    # -tabposition is a real ttk::notebook option, but only settable on the
    # widget instance itself (self.notebook.configure(tabposition=...)) --
    # style.configure() silently accepts and stores an option name it
    # doesn't recognize without raising, so an earlier attempt to hide the
    # native strip this way did nothing and just left both tab rows
    # showing at once ("duplicate tabs"). Emptying "TNotebook.Tab"'s own
    # element layout is the real, widely-used fix: with no elements to
    # draw, every native tab collapses to zero size, while every other
    # Notebook mechanic (.add/.tab/.select, hidden-vs-normal panel state,
    # <<NotebookTabChanged>>) keeps working underneath exactly as before --
    # none of that lives in the Tab element's layout.
    style.configure("TNotebook", background=APP_BG, borderwidth=0)
    style.layout("TNotebook.Tab", [])

    return family


# ---------------------------------------------------------------------------
# Canvas drawing helpers
# ---------------------------------------------------------------------------
def draw_logo_mark(canvas, size=28, pad=1):
    """Draw a small vector 'app icon' badge -- deliberately not an emoji or
    symbol-font glyph, since those aren't reliably available on every
    machine (headless/minimal Linux installs in particular)."""
    canvas.delete("all")
    rounded_rect(canvas, pad, pad, pad + size, pad + size, radius=7, fill=ACCENT, outline="")
    rounded_rect(canvas, pad + 5, pad + 5, pad + size - 5, pad + 10, radius=2, fill="white", outline="")
    canvas.create_oval(pad + 5, pad + 14, pad + 12, pad + 21, fill="white", outline="")
    canvas.create_oval(pad + size - 12, pad + 14, pad + size - 5, pad + 21, fill="white", outline="")


def draw_theme_swatch(canvas, theme_id: str, selected: bool, width=132, height=88):
    """Draw a small live preview card for one theme onto `canvas`, using
    that theme's own palette directly (not the app's currently-active
    globals above) -- this is what lets Settings show every preset side by
    side regardless of which one is actually active right now. Works for
    "custom" exactly like any other id -- get_theme() builds its palette
    live from the user's current seed colors either way.

    Mimics the real app's look in miniature: an app-background canvas, a
    panel "card" inset into it, and a couple of colored bars standing in
    for time blocks -- plus a filled corner badge when this is the
    currently-selected theme, the same "selected" convention used for
    project-color swatches elsewhere (see panels.ProjectPanel)."""
    canvas.delete("all")
    p = get_theme(theme_id)["palette"]

    rounded_rect(canvas, 1, 1, width - 1, height - 1, radius=10, fill=p["APP_BG"], outline="")

    card_pad = 10
    card_top = 10
    rounded_rect(canvas, card_pad, card_top, width - card_pad, height - 12,
                 radius=6, fill=p["PANEL_BG"], outline=p["BORDER"], width=1)

    # A couple of small "time block" bars in the accent + a muted neutral,
    # just enough to suggest the calendar without drawing the whole thing.
    bar_x = card_pad + 8
    bar_w = width - 2 * (card_pad + 8)
    rounded_rect(canvas, bar_x, card_top + 12, bar_x + bar_w, card_top + 26,
                 radius=3, fill=p["ACCENT"], outline="")
    rounded_rect(canvas, bar_x, card_top + 32, bar_x + bar_w * 0.62, card_top + 46,
                 radius=3, fill=p["BORDER_STRONG"], outline="")

    outline_color = p["ACCENT"] if selected else p["BORDER_STRONG"]
    outline_width = 3 if selected else 1
    rounded_rect(canvas, 1, 1, width - 1, height - 1, radius=10, outline=outline_color,
                 width=outline_width, fill="")

    if selected:
        badge_r = 9
        bx, by = width - 14, 14
        canvas.create_oval(bx - badge_r, by - badge_r, bx + badge_r, by + badge_r,
                            fill=p["ACCENT"], outline="")
        canvas.create_line(bx - 4, by, bx - 1, by + 3, bx + 4, by - 4,
                            fill="white", width=2, capstyle="round", joinstyle="round")


def rounded_rect(canvas, x1, y1, x2, y2, radius: float = 8, exponent: float = 4.0, **kwargs):
    """Draw a rounded rectangle on `canvas`, as a single polygon item.

    This has gone through two worse designs before landing here, both
    visible as real "artifacts" reported on real hardware (a Retina
    MacBook) that a plain-DPI Linux test environment never surfaced:

    1. Originally a single `create_polygon(..., smooth=True)` -- Tk's
       polygon smoothing approximates a spline *near* its control points
       rather than through them, which could leave a sliver of the
       canvas's flat background color poking out right at a corner.
    2. Then rewritten as several composited items per shape (quarter-circle
       "pieslice" arcs for the fill, plain arc outlines for the border,
       plus rectangles/lines for the straight edges) to get true circular
       corners. That fixed (1) but traded it for a worse, platform-specific
       problem: Tk's `create_arc` outline rendering (particularly with a
       thicker `width`, as the Settings theme-picker's selected-swatch ring
       uses) can draw past the arc's own bounding box at the start/end caps
       on some Tk builds -- visible as a small square notch poking out at
       a corner, exactly where the previous approach left a gap instead.

    This version samples real trigonometric points around each corner's
    true circular arc (no spline approximation) and draws the WHOLE shape
    -- all four corners and the straight edges between them -- as one
    `create_polygon` call, which natively supports fill AND outline
    together. One item means no seam between separately-drawn pieces is
    possible, and no per-item arc/line stroke-cap quirks either.

    `exponent` controls the corner *curve family*, not just its radius.
    2.0 is a true circular arc (the original design). Apple's "continuous
    corner" / squircle rounding used throughout iOS and macOS is smoother
    than a circular arc -- it keeps curving into the straight edge instead
    of meeting it at an abrupt tangent point -- and is commonly approximated
    with a superellipse of degree ~4-5. This defaults to 4.0 so every
    rounded shape in the app (buttons, cards, the calendar's own corners)
    reads as "Apple-style" without every call site needing to opt in.

    Returns the created item id (useful for the one caller --
    calendar_view._draw_entry -- that stacks its label text via
    `tag_raise(text_item, this_return_value)`).
    """
    x1, x2 = (x1, x2) if x1 <= x2 else (x2, x1)
    y1, y2 = (y1, y2) if y1 <= y2 else (y2, y1)
    radius = max(0.0, min(radius, (x2 - x1) / 2, (y2 - y1) / 2))

    if radius <= 0:
        return canvas.create_rectangle(x1, y1, x2, y2, **kwargs)

    # Each corner's own center plus the start/end angle (degrees, standard
    # math convention: 0=east, 90=north) of the quarter-circle arc that
    # belongs to it. Consecutive corners are listed so each one's end angle
    # picks up where the next begins (90 -> 0 -> -90 -> -180 -> back to 90),
    # one continuous sweep around the whole shape -- the straight edges
    # need no separate points at all, since a polygon already connects
    # consecutive points with straight lines, and each arc's sampled
    # endpoints already sit exactly on the straight edges (e.g. the
    # top-right corner's start point, at angle 90, is (x2-radius, y1) --
    # precisely where the top edge ends).
    corners = [
        (x2 - radius, y1 + radius, 90, 0),      # top-right
        (x2 - radius, y2 - radius, 0, -90),     # bottom-right
        (x1 + radius, y2 - radius, -90, -180),  # bottom-left
        (x1 + radius, y1 + radius, -180, -270),  # top-left
    ]
    steps = 10  # points per 90-degree corner -- plenty smooth at any size used in this app
    # Superellipse exponent: |cos|**(2/n) in place of plain cos generalizes
    # the circle (n=2, where 2/n=1 and this collapses back to plain cos)
    # into Apple's flatter-curved, longer-tangent "continuous corner" shape
    # for n>2. copysign keeps each term's original sign since abs() strips
    # it before the fractional power (a negative base to a fractional power
    # is undefined/complex in general).
    power = 2.0 / exponent
    points = []
    for cx, cy, start_deg, end_deg in corners:
        for i in range(steps + 1):
            deg = start_deg + (end_deg - start_deg) * i / steps
            rad = math.radians(deg)
            cos_v = math.cos(rad)
            sin_v = math.sin(rad)
            points.append(cx + radius * math.copysign(abs(cos_v) ** power, cos_v))
            # Canvas y increases downward (screen coordinates), unlike the
            # standard math y-axis this angle convention assumes -- so the
            # sign flips here to keep "up" (positive sin) meaning a
            # smaller y on screen.
            points.append(cy - radius * math.copysign(abs(sin_v) ** power, sin_v))
    return canvas.create_polygon(points, **kwargs)
